version: '3.8'

services:
  dotnet-api:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    container_name: dotnet-api
    ports:
      - "5000:80"
    depends_on:
      - sql-db
      - couchbase
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlDb=Server=sql-db;Database=mydb;User Id=sa;Password=yourStrong(!)Password;
      - ConnectionStrings__Couchbase=Server=couchbase;Username=Administrator;Password=password
      - Kafka__BootstrapServers=kafka:9092
    volumes:
      - ./src/RoulettApi:/app
    working_dir: /app
    command: ["dotnet", "YourDotnetApi.dll"]

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  sql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"

  couchbase:
    image: couchbase:community
    container_name: couchbase
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    environment:
      COUCHBASE_ADMINISTRATOR: "Administrator"
      COUCHBASE_ADMIN_PASSWORD: "password"
    volumes:
      - couchbase_data:/opt/couchbase/var

volumes:
  couchbase_data:
